name: Build & Release Silver Duck

permissions:
  contents: write  # required to create releases

on:
  push:
    branches: [ "main" ]     # build ZIP on pushes to main (artifact only)
    tags:
      - "v*"                 # full release on tags like v1.0.0
  workflow_dispatch: {}       # manual run (artifact only)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required files exist
        run: |
          test -f silver-duck.php
          test -f uninstall.php

      - name: Read versions
        id: versions
        shell: bash
        run: |
          PHP_VERSION="$(grep -Eo '^\s*\*\s*Version:\s*[0-9]+\.[0-9]+\.[0-9]+' silver-duck.php | head -1 | sed -E 's/.*Version:\s*//')"
          README_VERSION="$(grep -Eo '^Stable tag:\s*[0-9]+\.[0-9]+\.[0-9]+' readme.txt | head -1 | sed -E 's/^Stable tag:\s*//' || true)"
          echo "php_version=$PHP_VERSION" >> $GITHUB_OUTPUT
          echo "readme_version=$README_VERSION" >> $GITHUB_OUTPUT

      - name: Ensure tag and versions match (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"     # v1.0.0
          TAG_VERSION="${TAG#v}"             # 1.0.0
          echo "Tag: $TAG"
          echo "Plugin header Version: ${{ steps.versions.outputs.php_version }}"
          echo "readme Stable tag:    ${{ steps.versions.outputs.readme_version }}"
          test "${{ steps.versions.outputs.php_version }}" = "$TAG_VERSION"
          if [ -n "${{ steps.versions.outputs.readme_version }}" ]; then
            test "${{ steps.versions.outputs.readme_version }}" = "$TAG_VERSION"
          fi

      - name: Create distribution directory
        run: |
          mkdir -p dist/silver-duck
          cp silver-duck.php uninstall.php dist/silver-duck/
          [ -f README.md ] && cp README.md dist/silver-duck/
          [ -f readme.txt ] && cp readme.txt dist/silver-duck/

      - name: Make zip
        working-directory: dist
        run: zip -r silver-duck.zip silver-duck

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: silver-duck
          path: dist/silver-duck.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')   # only on tags like v1.0.0
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: silver-duck
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: silver-duck.zip
          generate_release_notes: true
