name: Build & Release Silver Duck

# ✅ Give the workflow permission to create releases
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]        # builds ZIP on pushes to main (artifact only)
    tags:
      - "v*"                    # full release when pushing tags like v1.0.0
  workflow_dispatch: {}          # manual run (builds artifact; release job still gated below)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify required files exist
        run: |
          test -f silver-duck.php
          test -f uninstall.php

      - name: Read versions
        id: versions
        shell: bash
        run: |
          PHP_VERSION="$(grep -Eo '^\s*\*\s*Version:\s*[0-9]+\.[0-9]+\.[0-9]+' silver-duck.php | awk '{print $3}')"
          README_VERSION="$(grep -Eo '^Stable tag:\s*[0-9]+\.[0-9]+\.[0-9]+' readme.txt | awk '{print $3}' || true)"
          echo "php_version=$PHP_VERSION" >> $GITHUB_OUTPUT
          echo "readme_version=$README_VERSION" >> $GITHUB_OUTPUT

      - name: Ensure tag and versions match (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"     # v1.0.0
          TAG_VERSION="${TAG#v}"             # 1.0.0
          echo "Tag: $TAG"
          echo "Plugin header Version: ${{ steps.versions.outputs.php_version }}"
          echo "readme Stable tag:    ${{ steps.versions.outputs.readme_version }}"
          test "${{ steps.versions.outputs.php_version }}" = "$TAG_VERSION"
          if [ -n "${{ steps.versions.outputs.readme_version }}" ]; then
            test "${{ steps.versions.outputs.readme_version }}" = "$TAG_VERSION"
          fi

      - name: Create distribution directory
        run: |
          mkdir -p dist/silver-duck
          cp silver-duck.php uninstall.php dist/silver-duck/
          [ -f README.md ] && cp README.md dist/silver-duck/
          [ -f readme.txt ] && cp readme.txt dist/silver-duck/

      - name: Make zip
        working-directory: dist
        run: zip -r silver-duck.zip silver-duck

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: silver-duck
          path: dist/silver-duck.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')   # only run on tag pushes like v1.0.0
    runs-on: ubuntu-latest
    # (Optional) also scope permissions here; redundant with top-level but harmless:
    permissions:
      contents: write
    steps:
      - uses:
